name: nightly

on:
  push:
    branches:
      - master
      - fix_ci
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.2
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.2"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Verify
        run: make verify
      - name: Test
        run: make test
      - name: Test sanity
        run: make test-sanity

  publish-nightly:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image nightly
      run: |
        make image-nightly
    - name: Login Docker Hub
      run: docker login --username juicefs --password ${PASSWORD}
      env:
        PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Buildx and Push docker image nightly
      run: make push-nightly
